### PR TITLE
add AMD logo

### PR DESCRIPTION
**Pull request by DhairyaLGandhi**
This adds the AMD logo to the front page of the website.
cc @jpsamaroo

@claforte Would you mind reviewing this and approving adding the AMD logo to the Flux website?

### CODE REVIEW

**Comment by claforte** [comment]
I think it's fine... I doubt we need to ask the lawyers for this. If so, I'll deal with the consequences.

**Comment by DhairyaLGandhi** [comment]
That's very kind, thank you! Would you mind approving the PR then if you don't mind?

**Comment by claforte** [comment]
I don't seem to have permission to add myself as reviewer... but I approve the PR. :-)

**Comment by DhairyaLGandhi** [comment]
Thanks so much!

**Pull request merged**
