### PR TITLE
Added environments

### PR DESCRIPTION
**Pull request by Roboneet**
Added environments for breakout, pong, go and chess

### CODE REVIEW

**Comment by xorJane** [comment]
Also bumping this! @MikeInnes 

Perhaps it would be easier to test/review if each game were a different PR? Mike do you have an opinion?

**Comment by Roboneet** [comment]
There are a few files in /tools/game with components that are common for all the games ( [css/style.css](https://github.com/Roboneet/fluxml.github.io/blob/92df24904da65703bfbe5e00c17f6b1874c807dd/tools/game/css/style.css), [js/game.js](https://github.com/Roboneet/fluxml.github.io/blob/92df24904da65703bfbe5e00c17f6b1874c807dd/tools/game/js/Game.js), and [js/helpers.js](https://github.com/Roboneet/fluxml.github.io/blob/92df24904da65703bfbe5e00c17f6b1874c807dd/tools/game/js/helpers.js)). I thought it might be a bit harder to maintain copies of them in different pull requests.

**Comment by MikeInnes** [comment]
Is it expected that I'm not seeing changes to the `experiments` page for this? How's best to give it a go?

**Comment by Roboneet** [comment]
I thought it would be best to add the links there after the models are added as well. But I could add it for the time being. Also, since the common structure part is almost completely developed, splitting into different PRs might be better, as @xorJane pointed out. @MikeInnes

**Comment by MikeInnes** [comment]
This is wild, I can't wait to get these working with models. Great work @Roboneet. It does make sense to merge these and add the links once they are done.

**Pull request merged**
