### PR TITLE
add more to tensorboard project

### PR DESCRIPTION
**Pull request by oxinabox**

### CODE REVIEW

**Comment by MikeInnes** [comment]
I would prefer to reword or remove the `useful skills` sections since it makes it seem a little like we need people to already be deeply familiar with logging etc. These are not to hard to pick up for someone who otherwise shows effort. Maybe "useful things to look into" instead.

**Comment by oxinabox** [comment]
*I* won't mentor a student who doesn't already know it.

It does say useful not required.

**Comment by MikeInnes** [comment]
Even if that student was clearly motivated enough to learn it own their own?

Even then that seems ok, we can co-mentor for some of the less tensorboard specific parts.

**Comment by oxinabox** [comment]
For me, motivation is not enough.
I am not dealing with GSOC students who are still learning julia, not this year.

**Comment by MikeInnes** [comment]
Why not? If a student can learn stuff on their own then it makes no odds to your workload, regardless of what they happen to know when reading this proposal.

**Comment by oxinabox** [comment]
year edit is acceptable to me

**Pull request merged**
