### PR TITLE
Add governance page

### PR DESCRIPTION
**Pull request by darsnack**
As a NumFOCUS affiliated project, we need to have a governance model publicly listed on our website. I have adopted the [SciML model](https://sciml.ai/governance/) following suggestions on Slack. We already follow the SciML ColPrac guide for contributions, so it makes sense to follow their governance model as well.

I have listed the current and former steering council members based on who has contributed to the project over the last year. I have not filled out the advisory committee yet. Once we adopt this model and the initial council, the steering council can ask some community members to join the committee (I can think of a few people already who graciously lend their advice on difficult issues).

### CODE REVIEW

**Comment by darsnack** [comment]
Pinging @CarloLucibello @mcabbott @ToucheSir @lorenzoh

**Comment by darsnack** [comment]
If someone can get Ruby running on their machine and verify the page build, then that would be appreciated. I'll tackle switching to Franklin in another PR.

**Review by CarloLucibello — APPROVED** [review]

**Comment by logankilpatrick** [comment]
General comment: It is awesome to see Flux adopt a public governance model!

**Comment by CarloLucibello** [comment]
I'm running the site locally and the change looks fine except for the section headers being right aligned which seems odd to me.
Screenshot 2022-08-09 at 16 37 03

**Comment by darsnack** [comment]
Okay I tweaked the formatting to look a little nicer. The right sided titles are an artifact of the website template, which I can fix later as part of the switch to Franklin.jl.

I will ask that the other current steering council members comment or approve to indicate their acceptance.

Screen Shot 2022-08-09 at 2 03 38 PM

**Review by ToucheSir — APPROVED** [review]

**Review by lorenzoh — APPROVED** [review]

**Comment by darsnack** [comment]
Bump @mcabbott on approval

**Review by mcabbott — APPROVED** [review]

**Pull request merged**
