### PR TITLE
gsod/getting started

### PR DESCRIPTION
**Pull request by lilianabs**

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
Can we get this in? We might have to revisit the getting started soon though. Good to start on the tutorials as well.

**Comment by logankilpatrick** [comment]
@lilianabs bumping this, it would be great to put the finishing touches on this before the end of the new year. I am trying to get a blog post up soon highlighting all the awesome work done during GSoD.

**Comment by lilianabs** [comment]
@DhairyaLGandhi would it possible to give more priority to this?

**Comment by logankilpatrick** [comment]
Not trying to step any anyone's toes, feel free to proceed with whatever was the original plan, just tossing out ideas :)

**Comment by lilianabs** [comment]
No problem @logankilpatrick :) Actually, we were planning on revisiting this new section very soon so we can have the final version.

**Comment by lilianabs** [comment]
I've improved this section. Any comments or suggestions are more than welcome :)

**Pull request closed without merging**
