### PR TITLE
Fix issues post move to Franklin.jl

### LINKED ISSUE #148: Port over assets from old site
Some posts still appear to need images and other files in https://github.com/FluxML/fluxml.github.io/tree/4be8e6cb60a08f43fbc7c7ea6b36d8cb8b44fe71/assets. e.g. the logos on https://fluxml.ai/blogposts/2021-12-1-flux-numfocus/.

### LINKED ISSUE #150: 404 error on Docs section
The docs section provided in the navbar is redirecting to a "page not found" error. The issue might be with the link provided 🤖

### PR DESCRIPTION
**Pull request by darsnack**
Fixes the documentation link which broke after the port. It also adds missing assets for the blogs and tutorials. Closes #148. Closes #150.

### CODE REVIEW

**Comment by darsnack** [comment]
@Saransh-cpp looks like the preview pre-path doesn't carry over to links in posts.

I also don't know why certain posts don't have the `title` page environment variable getting picked up. Seems like a Franklin issue (cc @tlienart)?

**Comment by tlienart** [comment]
@darsnack can you point me to a page that has the issue you're talking about? (are you talking about the `<title` tag not being set properly or something else?)

Just had a quick look around (maybe this should go in a separate issue btw so we can go through it gradually), there seems to be a few issues with image links e.g. https://fluxml.ai/blogposts/2021-12-1-flux-numfocus/

**Comment by darsnack** [comment]
I am merging this to resolve the asset and docs link issues. I'll open up a discussion specifically for the `hfun` issue.

**Comment by darsnack** [comment]
> can you point me to a page that has the issue you're talking about? or is it the items that get listed as Post 6 or Post 10? this is not an issue with Franklin but an issue with the function that does the listing of the posts; I'll have a look to see if I can fix it.

Sorry, I should have been more specific. I opened up #151 to track this.

**Comment by Saransh-cpp** [comment]
> looks like the preview pre-path doesn't carry over to links in posts.

Hmm, I think this is happening because the navbar points to the folders available in the root directory -

https://github.com/FluxML/fluxml.github.io/blob/be5b604cabbda353d87e06d150793525dd3b832d/_layout/navbar.html#L13-L28

I'll try to fix this.

**Comment by darsnack** [comment]
Not just the navbar but also image assets which are inserted like `/assets/...`

**Pull request merged**
