### PR TITLE
Add missing information - lost while porting

### PR DESCRIPTION
**Pull request by Saransh-cpp**
- add the GSoD page
- add the Governance page to the navbar
- comment out navbar links for GSoC and GSoD pages (as they were in the old website)
- add AMD's logo

### PR Checklist

- [ ] Tests are added
- [ ] Documentation, if applicable

### CODE REVIEW

**Comment by darsnack** [comment]
The navbar changes were intentional cause it was getting crowded. We could probably comment out GSoC too for now.

**Comment by Saransh-cpp** [comment]
Ah, my bad. Should I comment out the governance page from the navbar too?

**Comment by darsnack** [comment]
Yeah I would do that for now

**Comment by Saransh-cpp** [comment]
Done!

**Review by ToucheSir — APPROVED** [review]
Thanks!

**Pull request merged**
