### PR TITLE
lilianabs/gsod

### PR DESCRIPTION
**Pull request by lilianabs**
These are some initial updates to the site. You can see a preview of the changes [here](https://loving-bohr-270bc1.netlify.app/).

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Looks great so far!!!

**Comment by DhairyaLGandhi** [comment]
All the binary files that don't have changes should be removed from the PR, could you take that up?

**Comment by lilianabs** [comment]
> All the binary files that don't have changes should be removed from the PR, could you take that up?

Yes, I have removed them and resolved the conflict.

**Comment by DhairyaLGandhi** [comment]
Oops, looks like it deleted the files rather than removing them from the PR. Could you take a look please?

**Comment by lilianabs** [comment]
I'll try to remove the binary files or create a new PR.

**Comment by lilianabs** [comment]
I'm closing this PR to create a new one without unchanged binary files.

**Pull request closed without merging**
