### PR TITLE
Make Zygote's logo a real PNG

### PR DESCRIPTION
**Pull request by Saransh-cpp**
`Zygote`'s README renders this particular file. See https://github.com/FluxML/Zygote.jl/pull/1306.

### CODE REVIEW

**Comment by mcabbott** [comment]
Is this used on the website? Or just to have it hosted for use elsewhere?

**Comment by Saransh-cpp** [comment]
This is being used in Zygote's README. I think this can be removed and we can use the logo from Zygote's repository in its README? This feels a bit redundant, given that I couldn't find any other place where this is being used.

**Comment by Saransh-cpp** [comment]
Okay, this now removes the image from this repository. I've opened a PR in Zygote to use the locally available logo.

**Comment by Saransh-cpp** [comment]
This PR is completely empty now haha, closing this!

**Pull request closed without merging**
