### PR TITLE
CPPN: Animated Header

### PR DESCRIPTION
**Pull request by Roboneet**
Animated header with abstract patterns

### CODE REVIEW

**Comment by MikeInnes** [comment]
Very cool. A couple of small things --

* Might be good to have a translucent black rectangle behind the text now, so it doesn't get too bright underneath
* I think it could be slowed down a bit, right now it sometimes gets distracting
* Resolution occasionally looks a bit low (might be my HiDPI screen). Good to fix but only if it doesn't slow things down.
* Would be a nice touch if it faded over the original background image, after the weights are loaded -- otherwise it can be a bit jarring.
* Would be good to cite the original blog post, maybe with small text in the corner or something.

**Comment by MikeInnes** [comment]
I didn't realise before, but from your model-zoo PR it looks like there's no training actually required for this, is that right? In that case, perhaps we can just generate weights on the fly, rather than storing them?

**Comment by Roboneet** [comment]
Thanks, Mike! I've reduced the opacity of the canvas and it might've solved the first three problems. I've added custom weights, fading effect, and a link to the blog post as well.

**Comment by MikeInnes** [comment]
This is looking really good! I'm merging for now so we can get it in.

One question, is it possible to make the darker background full height? I think that might look just a tad better, but it's not too urgent if it's not easy.

**Pull request merged**
